name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Linode
        uses: appleboy/scp-action@master
        with:
          host: '172.232.206.68'
          username: 'deployuser'
          key: '-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEA/dwBjY4hmhVD456VAtmiISnmUkOVsFZA9sdnO7W1j5FXrNLdlwOE
ZNm/gCgooiiTO3hegpi3v0zaGWRMpW6cOb+L7uxTe+hDliNcBL/Ra6XOHFQm8g67i6gJRS
nvIu3E47em3nyAT6kC/+IJK268ON60+XEjCpA6BofsnyzGAgi2arOqfUVi7fa2BI7kefsh
c6zjUFZVvFbo3ZE1Ss0M9QM5+yPlaK6MCm8buihJHsDAGXsNskBliTSf+nxr6NgfREA3rO
tifNTs1aFwtJjblws+MPIu9o+2RIbIYXo4lE5mTwOLaciaErYyH2txrTaMG5yJNloHN+Ks
caedw3sWtkj8t5U+AFB95JuaIQbaiCCYr3t//3l6YPq/ehEKOgIwQuRGnrAXcbSEnhKGXD
oeI1dIkiXxZLxOlCtdSbOufSVxkWNkoOUDSbMH+3ZWjTrsGp7rZ1hZCRg7SDSdlfIiaXyS
B6OGAoHtbx+zksrwtea3vOKjDB0wWRzc+Av7LOABQA5s3oHdEWtgZ6lWM3fSIzvXhByXfw
B8UWNbNd7FHYoHFzy3PnFLbmUVhM5ZiLzgwVEdxSCMNY5wvSi7JK/UkB2j75EtmE0TqtuN
9J1aLuQfRLVVv0+8Oy3FpZHbsrni7JjXCEI1O0l+k7UO9bThhapHpdgQHkAJSmoUadW/8c
0AAAdIj6A6cY+gOnEAAAAHc3NoLXJzYQAAAgEA/dwBjY4hmhVD456VAtmiISnmUkOVsFZA
9sdnO7W1j5FXrNLdlwOEZNm/gCgooiiTO3hegpi3v0zaGWRMpW6cOb+L7uxTe+hDliNcBL
/Ra6XOHFQm8g67i6gJRSnvIu3E47em3nyAT6kC/+IJK268ON60+XEjCpA6BofsnyzGAgi2
arOqfUVi7fa2BI7kefshc6zjUFZVvFbo3ZE1Ss0M9QM5+yPlaK6MCm8buihJHsDAGXsNsk
BliTSf+nxr6NgfREA3rOtifNTs1aFwtJjblws+MPIu9o+2RIbIYXo4lE5mTwOLaciaErYy
H2txrTaMG5yJNloHN+Kscaedw3sWtkj8t5U+AFB95JuaIQbaiCCYr3t//3l6YPq/ehEKOg
IwQuRGnrAXcbSEnhKGXDoeI1dIkiXxZLxOlCtdSbOufSVxkWNkoOUDSbMH+3ZWjTrsGp7r
Z1hZCRg7SDSdlfIiaXySB6OGAoHtbx+zksrwtea3vOKjDB0wWRzc+Av7LOABQA5s3oHdEW
tgZ6lWM3fSIzvXhByXfwB8UWNbNd7FHYoHFzy3PnFLbmUVhM5ZiLzgwVEdxSCMNY5wvSi7
JK/UkB2j75EtmE0TqtuN9J1aLuQfRLVVv0+8Oy3FpZHbsrni7JjXCEI1O0l+k7UO9bThha
pHpdgQHkAJSmoUadW/8c0AAAADAQABAAACAAjzjQp3r3V05t4dTiGigXvx4kh/ONy+kMbF
zZoVCMAYUy7A5RdlBFrUNDwbLmf62e18XRXeiRNr+IBxzPT+NvBlQz0vswkuvxksj3hFlX
MI1Jh0lQDMDDGmqh54xG5HPA+KFkiaGRZY6d1vn7bJcS66XRl4yrj60JbMjDApaLwwK+oj
pShzev2OMjqx047PYZkiPPpyxUJv+EbU5iSIW4w9/xCrnHRZ9jEX/vh6j4ryynYy0yZEG2
e6yMT50c/qQHi3/eF/ydyH5v8XQ1HDp+Y3koulG6IZtbtBOFYpC6w9oadcsbnJi5a5r2iX
IDcIGtIaEGa7UlC/QLSrb6xUkPi/oF/Z4QfDpup6Zq3uMt3J9r6PHYui7jMsGSpexxXZQk
HiresnRAiO8w348caj6cX3gPkT9Yw07tFC2gDUn1MPnHR+UH5TqRmzMRKAPXuR8tLr1BLs
jk1rBklImv9KF350ovbddXL024WhuBdxTiZqtphyQAHhFoa3+scFSezC/5+WOkHHHfXGWy
cqUDD1WVuyKg6vfECZ5T2APyAPThGaIyspGzF1PrEL3byTrr+kqpdzV6plG4zG/JiMPHPU
FtEZGuJqaaKxOsTpi54j9wFh4qYWG3mGYMfsM4ny6hchs1vQvlAtfI91zxHaWs8u8DzyVz
/a1WJixWRXTI2LcO3xAAABAH10Ro0PLSI+wUuyGTXCv78M6iptzp2VFpWXtnWPP5Nfx5G5
NSiiFw9Ysin/3Raqcje5DrNqfenMG+1QZ1Ig+aDsttGMYj+oVwQ6yU/5/ja/hVQ9SwwWrz
saA9jeVzFvcVW9sJtrZU5S8Wt7geWsuongp7BNBrdXxYzWfcmsJOfg9XiccDLUgjmMVjZ+
3+zlXCW+G9MXzRnRCsgz+wwhnSAuON0kvbv/0fh2rb4SY0rFTn+jP7XvNWcJdYjnNGaSea
2ZDfpaWCLOvM+obc4Kokv0hyfpUDGylp3DSQbvX3aVpnWLyb7Pn1/5Pi9dou+XNkyGoJDA
YVXMZjOSs/HBDVoAAAEBAP9Glv4gjlSR6eufDzb9nGnvBBEIaUYn4LMS0B/2hFhH575RrH
CnXBr2/OFD0asaVxYns5h8mYC8I41Qqgbkd+g0XSpgyXTAy7VYQi9hTkJy9c4G+5F1/1f7
kFZFmN3iO+8rgqNZtFeVYz0VhhtEXVqMELZLvgNiKevbOP9tRxTE4qu6DE/tCtgXJw1cBg
wdG0fA8Z2VftLADeqoO4LGjEdmh8QY6H7K2z3c+19LDxhHMD7GVRMwT/0xzI1bo6pK+cgA
sMKwBupYi3N1eJmLemVCdyvsV9Hoi/d6FwGQ8kvs+6T+N8TcI6ove0FqVh4uCZs1dw7xNt
XmtvqbsGGuHgMAAAEBAP6UYzX5nM9k1a6vLfQHlQM48H894NU39pQ3Kog4N6jt2UrMI0Mc
9ZEECnPgQX/IQJywVYbM9JxcIwIS0oDnTRoBK54Y4QJE9bh+toNsyZFTGcQ72l19qw8n/1
+KjkKXIQzR+Ejjyi8GMnW+Bs+u3824WqrHuKZEuBQJ35cvXg7UJcqBbufiwReN2Os+0ffg
vlQMz2UFndnc9bijzCrQgPaG/3fqJY8RDwXXCuh24imHWIBKt5cSxng9Lb7KxWch99QhBb
4hPLcVUj/f4YjbXarEjjVULOp1AXE1Z5Rlg8k/pxofNUKdJYofJ9ff/dv4yNXEO6/tYbKC
JUPJPNulT+8AAAAOZGV2QHR1cmtpLnRlY2gBAgMEBQ==
-----END OPENSSH PRIVATE KEY-----'
          port: '22'
          source: './dist/*'
          target: '/var/www/cicd-test-linode'
